### ISSUE TITLE
What is the real Mult-Adds?

### ISSUE THREAD

**Issue by yumath** [MingSun-Tse/ASSL#6]
Hi, we directly using your test scripts with provided [final models](https://github.com/MingSun-Tse/ASSL/releases) to testing on benchmark(Set5, Set14, B100, Urban100, Manga109), we got x2 results below:
  |x2| Set5 | Set14 | B100 | Urban100 | Manga109 |
  |--|--|--|--|--|--|
  |PSNR|38.04|33.71|32.22|32.24|38.87|

But it's far below with results reported in the paper, benchmark x2 results in the paper reported:
  |x2| Set5 | Set14 | B100 | Urban100 | Manga109 |
  |--|--|--|--|--|--|
  |PSNR|38.12|33.77|32.27|32.41|39.12|

Only if using the _**--self-ensemble**_ parameter when testing, we can get comparable results to the paper. 
results of provided [final models](https://github.com/MingSun-Tse/ASSL/releases) testing with  _**--self-ensemble**_ parameter below:
  |x2| Set5 | Set14 | B100 | Urban100 | Manga109 |
  |--|--|--|--|--|--|
  |PSNR|38.12|33.77|32.26|32.40|39.09|

So, Does the result in the paper used the _**--self-ensemble**_ parameter?
But, If _**--self-ensemble**_ used, the model need forward per image 8 times for ensemble, and the Mult-Adds of R16F48 should be 159.1 G x 8 = 1272.8 G

**Comment by MingSun-Tse** [comment]
Hi @yumath , thanks for your interest in our paper! We double-checked the model. Your understanding is correct -- the results in the paper is evaluated using --self-ensemble, which means the FLOPs should be multiplied by x8. Without self-ensemble, the advantage of our method over others should shrink to a certain degree, up to the specific test dataset and scale. Thanks for pointing this out! We shall upload an updated version to arxiv to correct this.

**Comment by yumath** [comment]
Thanks for your reply, it's very helpful ! @MingSun-Tse
